// 'use client';
import Link from 'next/link';
import './globals.css';
// import { useEffect, useState } from 'react';

export const metadata = {
    title: 'Web tutuorials',
    description: 'Generated by Juhyang',
};

export default async function RootLayout({ children }) {
    // const [topics, setTopics] = useState([]);
    // useEffect(() => {
    //     fetch('http://localhost:9999/topics')
    //         .then((resp) => resp.json())
    //         .then((result) => {
    //             setTopics(result);
    //         });
    // }, []);

    //fetch도 동기적인 코드로 바꾸기
    const resp = await fetch('http://localhost:9999/topics');
    const topics = await resp.json();

    // console.log(topics);

    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>

                <header>
                    {/* <ol>
                        <li>
                            <Link href="/read/1">html</Link>
                        </li>
                        <li>
                            <Link href="/read/2">css</Link>
                        </li>
                    </ol> */}

                    <ol>
                        {topics.map((topic) => (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>
                                    {topic.title}
                                </Link>
                            </li>
                        ))}
                    </ol>
                </header>

                {children}

                <aside>
                    <ul>
                        <li>
                            <Link href="/create">Create</Link>
                        </li>
                        <li>
                            <Link href="/update/1">Update</Link>
                        </li>
                        <li>
                            <input type="button" value="Delete" />
                        </li>
                    </ul>
                </aside>
            </body>
        </html>
    );
}
