import './globals.css';

export const metadata = {
    title: 'Web tutuorials',
    description: 'Generated by Juhyang',
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <h1>
                    <a href="/">WEB</a>
                </h1>
                <header>
                    <ol>
                        <li>
                            <a href="/read/1">html</a>
                        </li>
                        <li>
                            <a href="/read/2">css</a>
                        </li>
                    </ol>
                </header>
                {children}
                <aside>
                    <ul>
                        <li>
                            <a href="/create">Create</a>
                        </li>
                        <li>
                            <a href="/update/1">Update</a>
                        </li>
                        <li>
                            <input type="button" value="Delete" />
                        </li>
                    </ul>
                </aside>
            </body>
        </html>
    );
}
